export interface CoffeeList {
    _id: string,
    name: string,
    quantity: number | string,
    rating: number,
    ingredient: string,
    roasted: string,
    type: "CAPSULES" | "BEANS",
    description: string,
    image_url: string,
    link: string,
}

export const CoffeeListData: CoffeeList[] = [
    {
        "_id": "65da6b9a3cd43e55cd15c558",
        "name": "Cappuccino",
        "ingredient": "Agua",
        "roasted": "Arabica",
        "type": "CAPSULES",
        "quantity": 10,
        "rating": 5,
        "description": "Um clássico italiano pronto em questão de segundos. Você vai adorar a camada generosa e sedutora de espuma de leite integral se encontrando com um espresso intenso, feito com os melhores grãos de café.",
        "image_url": "https://www.nescafe-dolcegusto.com.br/media/catalog/product/cache/d22af66f75f51f60e100631e2c10a99a/3/_/3_1_4_1.webp",
        "link": "https://www.nescafe-dolcegusto.com.br/cappuccino-capsulas-10",
    },
    {
        "_id": "65da6bed3cd43e55cd15c55c",
        "name": "Pingado",
        "ingredient": "Agua",
        "roasted": "Arabica",
        "type": "CAPSULES",
        "quantity": 10,
        "rating": 5,
        "description": "A harmonia perfeita da suavidade entre o café e o leite, preparado do jeitinho que você gosta. Se surpreenda com o Pingado, que tem uma espuma cremosa e é a bebida perfeita para as pausas da manhã ou da tarde!",
        "image_url": "https://www.nescafe-dolcegusto.com.br/media/catalog/product/cache/d22af66f75f51f60e100631e2c10a99a/x/i/xicara_reta_1_1.webp",
        "link": "https://www.nescafe-dolcegusto.com.br/sabores/capsulas-pingado-10",
    },
    {
        "_id": "65da6c503cd43e55cd15c55f",
        "name": "Café caseiro",
        "ingredient": "Agua",
        "roasted": "Arabica",
        "type": "CAPSULES",
        "quantity": 10,
        "rating": 5,
        "description": "Um café desenvolvido especialmente para os brasileiros que traz o sabor, o frescor e o aroma único do café coado e passado na hora ao toque de um botão. Descubra essa bebida suave, de média intensidade e feita com grãos 100% Arábica.",
        "image_url": "https://www.nescafe-dolcegusto.com.br/media/catalog/product/cache/d22af66f75f51f60e100631e2c10a99a/c/a/cafe-caseiro-cup-capsule-side_1_1_1_1.webp",
        "link": "https://www.nescafe-dolcegusto.com.br/sabores/capsulas-cafe-caseiro-10",
    }
]


export const BeanListData: CoffeeList[] = [
    {
        "_id": "65da6b9a3cd43e55cd15bean",
        "name": "Café raro",
        "ingredient": "Agua",
        "roasted": "Arabica",
        "type": "BEANS",
        "quantity": "250g",
        "rating": 5,
        "description": "Café da variedade Gesha cultivado na Fazenda Santa Mônica na Alta Mogiana Mineira pelo produtor Jean Faleiros. Muito bem avaliado por degustadores profissionais, esse lote é uma verdadeira raridade. Depois de passar por um processo de fermentação natural esse café adquiriu notas de vinho branco e acidez málica! Peso líquido: 250g.",
        "image_url": "https://cdn.dooca.store/63955/products/raro_620x620.jpg?v=1682469571",
        "link": "https://loja.encantosdocafe.com.br/cafe-raro-250g",
    },
    {
        "_id": "65da6bed3cd43e55cd15bean",
        "name": "Café agrado",
        "ingredient": "Agua",
        "roasted": "Arabica",
        "type": "BEANS",
        "quantity": "250g",
        "rating": 5,
        "description": "Café da variedade Bourbon Vermelho produzido pela Fazenda Irmãs Pereira no Sul de Minas. Secado por um processo natural, esse grão é oferecido com uma torra média escura. Suas notas sensoriais lembram mel e cacau. Peso líquido: 250g.",
        "image_url": "https://cdn.dooca.store/63955/products/agrado_620x620.jpg?v=1682469664",
        "link": "https://loja.encantosdocafe.com.br/cafe-agrado-250g",
    },
    {
        "_id": "65da6c503cd43e55cd15bean",
        "name": "Blend sensação",
        "ingredient": "Agua",
        "roasted": "Arabica",
        "type": "BEANS",
        "quantity": "250g",
        "rating": 5,
        "description": "Blend de lotes diferentes da mesma variedade, catucaí vermelho! Cafés cultivados na mesma região e com o mesmo processo pós colheita, honey. Uma composição de sabores que leva a um café rico em doçura, fácil de beber e com notas sensoriais de mel e rapadura. Peso líquido: 250g.",
        "image_url": "https://cdn.dooca.store/63955/products/sensacao_620x620.jpg?v=1682469613",
        "link": "https://loja.encantosdocafe.com.br/cafe-blend-sensacao-250g",
    },
    {
        "_id": "65fa6c503cd43e55cd15bean",
        "name": "Café desejo",
        "ingredient": "Agua",
        "roasted": "Arabica",
        "type": "BEANS",
        "quantity": "250g",
        "rating": 5,
        "description": "Café da variedade Catuaí Amarelo produzido pela Fazenda Lagoinha no Sul de Minas. Esse grão passou por um processo pós colheita com fermentação induzida por leveduras. Muito saboroso e com uma acidez exótica, esse café tem notas sensoriais de frutas vermelhas e aroma floral. Peso líquido: 250g.",
        "image_url": "https://cdn.dooca.store/63955/products/desejo_620x620.jpg?v=1682469636",
        "link": "https://loja.encantosdocafe.com.br/cafe-desejo-250g",
    }
]